import { service } from "../../types/service";

export const servicesFaker: service[] = [
    {
        id: 1,
        user_id_get: undefined,
        user_id_do: 2,
        type: "Offre",
        title: "Titre du service #1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vestibulum risus et ex euismod accumsan. Pellentesque eu egestas leo, at tincidunt lorem.",
        category: "Bricolage",
        skill_level: 1,
        hard_level: 3,
        created_at: "Nov 1, 24 00:20:18",
        updated_at: "Nov 1, 24 00:20:18",
        terminated: false,
        picture: "https://www.bricopro.fr/sites/default/files/styles/home_slider/public/universe/header-bricolage-iStock-1147804793.jpg?itok=hMNAUG16",
    },
    {
        id: 2,
        user_id_get: undefined,
        user_id_do: 1,
        type: "Offre",
        title: "Titre du service #2",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vestibulum risus et ex euismod accumsan. Chat pellentesque eu egestas leo, at tincidunt lorem.",
        category: "Extérieur",
        skill_level: 2,
        hard_level: 4,
        created_at: "Nov 16, 24 00:20:18",
        updated_at: "Nov 16, 24 00:20:18",
        terminated: false,
        picture: "https://www.ootravaux.fr/sites/ootravaux/storage/files/2022-07/prix-tonte-pelouse-jardin.jpg",
    },
    {
        id: 3,
        user_id_get: 1,
        user_id_do: 3,
        type: "Demande",
        title: "Titre du service #3",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vestibulum risus et ex euismod accumsan. Pellentesque eu egestas leo, at tincidunt lorem.",
        category: "Extérieur",
        skill_level: 1,
        hard_level: 2,
        created_at: "Nov 10, 24 00:20:18",
        updated_at: "Nov 10, 24 00:20:18",
        terminated: false,
        picture: "https://www.ootravaux.fr/sites/ootravaux/storage/files/2022-07/prix-tonte-pelouse-jardin.jpg",
    },
    {
        id: 4,
        user_id_get: 4,
        user_id_do: undefined,
        type: "Demande",
        title: "Titre du service #4",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vestibulum risus et ex euismod accumsan. Pellentesque eu egestas leo, at tincidunt lorem.",
        category: "Courses",
        skill_level: 5,
        hard_level: 6,
        created_at: "Oct 20, 24 00:20:18",
        updated_at: "Oct 20, 24 00:20:18",
        terminated: false,
        picture: "",
    },
    {
        id: 5,
        user_id_get: 5,
        user_id_do: 1,
        type: "Offre",
        title: "Titre du service #5",
        description: "Lorem ipsum dolor sit amet, bricolage consectetur adipiscing elit. Phasellus vestibulum risus et ex euismod accumsan. Pellentesque eu egestas leo, at tincidunt lorem.",
        category: "Garderie",
        skill_level: 4,
        hard_level: 4,
        created_at: "Nov 18, 24 00:20:18",
        updated_at: "Nov 18, 24 00:20:18",
        terminated: true,
        picture: "https://assets.elanco.com/8e0bf1c2-1ae4-001f-9257-f2be3c683fb1/0d883951-1bd2-4087-8a33-a56a2f58aede/comment_garder_son_chien_en_securite_durant_une_promenade.jpg",
    },
    {
        id: 6,
        user_id_get: 1,
        user_id_do: 8,
        type: "Demande",
        title: "Titre du service #6",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vestibulum risus et ex euismod accumsan. Pellentesque eu egestas leo, at tincidunt lorem.",
        category: "Soutien",
        skill_level: 3,
        hard_level: 3,
        created_at: "Nov 3, 24 00:20:18",
        updated_at: "Nov 3, 24 00:20:18",
        terminated: false,
        picture: "https://vousparmacif.macif.fr/sites/default/files/styles/image_intro_article/public/2021-12/garde-d-enfant-quelles-aides-pour-alleger-votre-budget.jpg?itok=-and-vun",
    },
];
