import { userProfile } from "../../types/user";

export const usersFaker: userProfile[] = [
    {
        id: 0,
        email: "email@deja-enregistré.com",
        password: "",
        acceptTerms: true,
        stayConnected: true,
        firstName: "Test",
        lastName: "test",
        avatar: "https://w7.pngwing.com/pngs/340/946/png-transparent-avatar-user-computer-icons-software-developer-avatar-child-face-heroes.png",
        phone: "phoneteste",
        adress_shared: true,
        assistant: 0,
        points: 20,
        adress: "4 Rue de Louzillais, 35740 Pacé",
        skills: ["test1", "teste2"],
    },
    {
        id: 1,
        email: "agnes.dupont@deja-enregistré.com",
        password: "",
        acceptTerms: true,
        stayConnected: true,
        firstName: "Agnes",
        lastName: "Dupont",
        avatar: "https://www.perfocal.com/blog/content/images/size/w960/2021/01/Perfocal_17-11-2019_TYWFAQ_100_standard-3.jpg",
        phone: "06090909909",
        adress_shared: true,
        assistant: 1,
        points: 10,
        adress: "4 Rue de Louzillais, 35740 Pacé",
        skills: ["HTML", "CSS", "JS"],
    },
    {
        id: 2,
        email: "test@test.fr",
        password: "",
        acceptTerms: true,
        stayConnected: true,
        firstName: "Thimothé",
        lastName: "Tremblay",
        avatar: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1480&q=80",
        phone: "",
        adress_shared: true,
        assistant: 2,
        points: 50,
        adress: "6 rue de la gare 13003 Marseille",
    },
    {
        id: 3,
        email: "test2@test.fr",
        password: "",
        acceptTerms: true,
        stayConnected: true,
        firstName: "Julien",
        lastName: "Lecoq",
        avatar: "https://images.ctfassets.net/h6goo9gw1hh6/2sNZtFAWOdP1lmQ33VwRN3/24e953b920a9cd0ff2e1d587742a2472/1-intro-photo-final.jpg?w=1200&h=992&q=70&fm=webp",
        phone: "",
        adress_shared: true,
        assistant: 3,
        points: 15,
        adress: "8 boulvard de la gare 53200 Nantes",
    },
    {
        id: 4,
        email: "ABC",
        password: "",
        acceptTerms: true,
        stayConnected: true,
        firstName: "Benjamin",
        lastName: "Dupont",
        avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80",
        phone: "",
        adress_shared: true,
        assistant: 0,
        points: 34,
        adress: "stade de velodrome 13008, Marseille",
    },
    {
        id: 5,
        email: "",
        password: "",
        acceptTerms: true,
        stayConnected: true,
        firstName: "Marie",
        lastName: "Tremblay",
        avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1288&q=80",
        phone: "",
        adress_shared: true,
        assistant: 1,
        points: 10,
        adress: "60 traverse du moulin de la villette 13003 Marseille",
    },
    {
        id: 6,
        email: "",
        password: "",
        acceptTerms: true,
        stayConnected: true,
        firstName: "Julia",
        lastName: "Lecoq",
        avatar: "https://fac.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2FFAC.2Fvar.2Ffemmeactuelle.2Fstorage.2Fimages.2Famour.2Fcoaching-amoureux.2Fcest-quoi-belle-femme-temoignages-43206.2F14682626-1-fre-FR.2Fc-est-quoi-une-belle-femme-temoignages.2Ejpg/1200x1200/quality/80/crop-from/center/c-est-quoi-une-belle-femme-temoignages.jpeg",
        phone: "",
        adress_shared: true,
        assistant: 2,
        points: 10,
        adress: "19 rue saint jean 13008 Marseille",
    },
    {
        id: 7,
        email: "",
        password: "",
        acceptTerms: true,
        stayConnected: true,
        firstName: "Marie",
        lastName: "Dupont",
        avatar: "https://www.perfocal.com/blog/content/images/size/w960/2021/01/Perfocal_17-11-2019_TYWFAQ_100_standard-3.jpg",
        phone: "",
        adress_shared: true,
        assistant: 0,
        points: 10,
        adress: "",
    },
    {
        id: 8,
        email: "",
        password: "",
        acceptTerms: true,
        stayConnected: true,
        firstName: "George",
        lastName: "Tremblay",
        avatar: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1480&q=80",
        phone: "",
        adress_shared: true,
        assistant: 2,
        points: 10,
        adress: "",
    },
    {
        id: 9,
        email: "",
        password: "",
        acceptTerms: true,
        stayConnected: true,
        firstName: "Julien",
        lastName: "Lecoq",
        avatar: "https://images.ctfassets.net/h6goo9gw1hh6/2sNZtFAWOdP1lmQ33VwRN3/24e953b920a9cd0ff2e1d587742a2472/1-intro-photo-final.jpg?w=1200&h=992&q=70&fm=webp",
        phone: "",
        adress_shared: true,
        assistant: 3,
        points: 10,
        adress: "",
    },
    {
        id: 10,
        email: "",
        password: "",
        acceptTerms: true,
        stayConnected: true,
        firstName: "Timothé",
        lastName: "Dupont",
        avatar: "https://www.perfocal.com/blog/content/images/size/w960/2021/01/Perfocal_17-11-2019_TYWFAQ_100_standard-3.jpg",
        phone: "",
        adress_shared: true,
        assistant: 0,
        points: 10,
        adress: "",
    },
    {
        id: 11,
        email: "",
        password: "",
        acceptTerms: true,
        stayConnected: true,
        firstName: "Marie",
        lastName: "Tremblay",
        avatar: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1480&q=80",
        phone: "",
        adress_shared: true,
        assistant: 2,
        points: 10,
        adress: "",
    },
    {
        id: 12,
        email: "",
        password: "",
        acceptTerms: true,
        stayConnected: true,
        firstName: "Julien",
        lastName: "Lecoq",
        avatar: "https://images.ctfassets.net/h6goo9gw1hh6/2sNZtFAWOdP1lmQ33VwRN3/24e953b920a9cd0ff2e1d587742a2472/1-intro-photo-final.jpg?w=1200&h=992&q=70&fm=webp",
        phone: "",
        adress_shared: true,
        assistant: 0,
        points: 10,
        adress: "",
    },
];
